spring:
  datasource:
    username: root
    password: example
    url: jdbc:mysql://localhost:3306/jpaData
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create


decorator:
  datasource:
    p6spy:
      enable-logging: true
